meta:
  schema-version: 0.1.0
  created-on: "2024-02-15T11:42:29Z"
  cli-version: 0.2.0
projects:
  2lambda123-blockchain:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "5"
    overrides:
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      minimist:
        1.2.0:
          use: 1.2.0-sp1
      got:
        6.7.1:
          use: 6.7.1-sp1
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      set-value:
        0.4.3:
          use: 0.4.3-sp1
      glob-parent:
        3.1.0:
          use: 3.1.0-sp1
      ansi-regex:
        3.0.0:
          use: 3.0.0-sp1
      nth-check:
        1.0.2:
          use: 1.0.2-sp1
      ini:
        1.3.5:
          use: 1.3.5-sp1
      ip:
        1.1.5:
          use: 1.1.5-sp1
